### Mod properties
mod.name="Extra Animations"
mod.id="extra_animations"
mod.version='1.0'
mod.description="Adds some missing animations to the game"

### Publishing
mod.modrinth="R2MIQqZs"
mod.curseforge="1565468"
mod.github="extra-animations"

### Subprojects
["26.2"]
pub-end="latest"

["1.21.8"]
pub-start="1.21.7"
pub-end="1.21.11"
